services:
    app:
        container_name: katanoko

        build:
            context: ./app
            dockerfile: Dockerfile

        volumes:
            - /home/.gemini/:/workspace/.gemini:cached
            - ../:/workspace:cached
            - /var/run/docker.sock:/var/run/docker.sock

        env_file: ./app/.env

        command: sleep infinity

        depends_on:
            - pg-17

    pg-17:
        container_name: katanoko-pg-17

        build:
            context: ./pg/pg-17
            dockerfile: Dockerfile

        restart: unless-stopped

        volumes:
            - postgres-data:/var/lib/postgresql/data

        env_file: ./pg/.env

        ports:
            - '48917:5432'

volumes:
    postgres-data:
